# -*- coding: utf-8 -*-
"""Smart_School_Management_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAMzfyykClrPk3iqAYTSqaKTec6KRkjx
"""

#importing the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn import preprocessing
from sklearn.cluster import KMeans
from collections import Counter
from itertools import product
from bioinfokit.visuz import cluster
from sklearn.cluster import KMeans
from yellowbrick.cluster import KElbowVisualizer
from statsmodels.graphics.mosaicplot import mosaic
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import r2_score as r2
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import precision_score,recall_score,f1_score
import math
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('StudentsPerformance.csv')
df2=pd.read_csv('teacher_performance_evaluation.csv')
df3=pd.read_csv('smart_school_app_competitors.csv')

df.head()

from mimesis import Person
person = Person('en')

# function to create names to exact rows
def fake_names(n):
   name = []
   for _ in range(0, n):
        name.append(person.name())
   return name

names = fake_names(1000)

df_name = pd.DataFrame(list(zip(names)),columns = ['Name'])

df_name.head()

df1 = pd.concat([df_name, df], axis=1).reindex(df.index)
df1.head()

#create new column Total_score
df1['Total_Performance_Score'] = df1[['math score', 'reading score', 'writing score']].mean(axis=1)
df1

#create new column performance level
# Function to determine performance level
def performance_level(score):
    if score > 80:
        return 'high'
    elif score > 60:
        return 'medium'
    else:
        return 'low'

# Apply the function to create a new column
df1['Performance_Level'] = df1['Total_Performance_Score'].apply(performance_level)
df1=pd.DataFrame(df1)
df1

df1.info()

df1.columns

"""EDA and Preprocessing for Student Performance"""

df1['race/ethnicity'].value_counts()

df1['Performance_Level'].value_counts()

df1['gender'].value_counts()

df1['parental level of education'].value_counts()

df1['test preparation course'].value_counts()

df1['lunch'].value_counts()

#univariate analysis of categorical variables
fig, ax = plt.subplots(3, 2, figsize = (18,18))
_=sns.countplot(df1['gender'], ax=ax[0,0], palette='Set2')
_=sns.countplot(df1['parental level of education'], ax=ax[0,1], palette='Set2')
_=sns.countplot(df1['lunch'], ax=ax[1,0], palette='Set2')
_=sns.countplot(df1['test preparation course'], ax=ax[1,1], palette='Set2')
_=sns.countplot(df1['race/ethnicity'], ax=ax[2,0], palette='Set2')
_=sns.countplot(df1['Performance_Level'], ax=ax[2,1], palette='Set2')

#univariate analysis of numerical columns - continuous variables -
df1[['math score','reading score','writing score','Total_Performance_Score']].hist(figsize=(10,5))
plt.show()

# Demographic segmentation using 'race/ethnicity' & 'gender'

# Gender: we infer that there are more female customers than male
labels = ['Female', 'Male']
size =df1['gender'].value_counts()
colors = ['green', 'crimson']
explode = [0, 0.1]
plt.rcParams['figure.figsize'] = (7, 7)
plt.pie(size, colors = colors, explode = explode, labels = labels, shadow = True, autopct = '%.2f%%')
plt.title('gender', fontsize = 20)
plt.axis('off')
plt.legend()
plt.show()

# Age: Mcdonalds recieve more customers of age between 50-60 and 35-40
plt.rcParams['figure.figsize'] = (15, 8)
data3 = sns.countplot(x=df1['race/ethnicity'], palette = 'rocket_r')
# Add bar labels
for container in data3.containers:
    data3.bar_label(container)
plt.title('Race distribution of customers', fontsize = 20)
plt.show()

plt.figure(figsize=(6, 6))
prep_score = df1.groupby('test preparation course')['Total_Performance_Score'].nunique().plot(kind='bar')
plt.title("Test Preparation vs Total_Performance_Score", fontsize = 10)

plt.figure(figsize=(6, 6))
prep_score = df1.groupby('Performance_Level')['Total_Performance_Score'].nunique().plot(kind='bar')
plt.title("Performance_Level vs Total_Performance_Score", fontsize = 10)

plt.figure(figsize=(6, 6))
prep_score = df1.groupby('parental level of education')['Total_Performance_Score'].nunique().plot(kind='bar')
plt.title("Parental level of education vs Total_Performance_Score", fontsize = 10)

print(f"Duplicates: {df1.duplicated().sum()}")
duplicate = df1[df1.duplicated()]
duplicate

df1[['math score','reading score','writing score','Total_Performance_Score']].describe()

# Name column don't add any value.
df1.drop(['Name'], axis=1, inplace=True);

#Boxplot for numerical column
for i in ['math score','reading score','writing score']:
    plt.figure()
    plt.boxplot(df1[i])
    plt.title(i)

#change the column names

df1.rename(columns={'math score':'math_score','reading score':'reading_score','writing score':'writing_score'},inplace=True)

#To treat outliers
Q1 = df1.math_score.quantile(0.25)
Q3 = df1.math_score.quantile(0.75)
IQR = Q3 - Q1
min_limit = Q1 - (IQR * 1.5)
max_limit = Q3 + (IQR * 1.5)
print(min_limit, max_limit,IQR)

df1.loc[df1['math_score']>max_limit,'math_score']=np.median(df1.math_score)
df1.loc[df1['math_score']<min_limit,'math_score']=np.median(df1.math_score)

Q1 = df1.reading_score.quantile(0.25)
Q3 = df1.reading_score.quantile(0.75)
IQR = Q3 - Q1
min_limit = Q1 - (IQR * 1.5)
max_limit = Q3 + (IQR * 1.5)
print(min_limit, max_limit,IQR)

df1.loc[df1['reading_score']>max_limit,'reading_score']=np.median(df1.reading_score)
df1.loc[df1['reading_score']<min_limit,'reading_score']=np.median(df1.reading_score)

Q1 = df1.writing_score.quantile(0.25)
Q3 = df1.writing_score.quantile(0.75)
IQR = Q3 - Q1
min_limit = Q1 - (IQR * 1.5)
max_limit = Q3 + (IQR * 1.5)
print(min_limit, max_limit,IQR)

df1.loc[df1['writing_score']>max_limit,'writing_score']=np.median(df1.writing_score)
df1.loc[df1['writing_score']<min_limit,'writing_score']=np.median(df1.writing_score)

#Label Encoding
le=LabelEncoder()
df1['gender']=le.fit_transform(df1['gender'])
df1['race/ethnicity']=le.fit_transform(df1['race/ethnicity'])
df1['parental level of education']=le.fit_transform(df1['parental level of education'])
df1['lunch']=le.fit_transform(df1['lunch'])
df1['test preparation course']=le.fit_transform(df1['test preparation course'])
df1['Performance_Level']=le.fit_transform(df1['Performance_Level'])

df1

"""To predict Student Preferances about the course recommendation"""

#Splitting the data into independent and dependent variables
X=df1.drop(['test preparation course','lunch','gender','Performance_Level'],axis=1)
y=df1['test preparation course']

## Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = MinMaxScaler()
numeric_features = []

for col in X.columns:
    if(X[col].dtype == "float" ):
        numeric_features.append(col)

X[numeric_features] = scaler.fit_transform(X[numeric_features])
X

from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier()
model.fit(X,y)
#use inbuilt class feature_importances of tree
print(model.feature_importances_)
#plot graph of feature importance
feat_importances=pd.Series(model.feature_importances_,index=X.columns)
feat_importances.nlargest(7).plot(kind='barh')

#splitting the data into train ,test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 42, test_size = 0.2 )

print(X_train.shape),print(y_train.shape)
print(X_test.shape),print(y_test.shape)

"""Modeling and Evaluation"""

#Naive Bayes, Support Vector Machines (SVM), Random Forest,KNN,Linear Support Vector Machine,Logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from xgboost import XGBClassifier
from sklearn.svm import SVC

#1.using LogisticRegression
log_reg=LogisticRegression()
model = log_reg.fit(X_train,y_train)
log_pred = model.predict(X_test)
cm=confusion_matrix(y_test,log_pred)
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
print(classification_report(y_test,log_pred))

#2.using RandomForestClassifier
rf_clf=RandomForestClassifier()
model = rf_clf.fit(X_train,y_train)
rf_pred = model.predict(X_test)
cm=confusion_matrix(y_test,rf_pred)
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
print(classification_report(y_test,rf_pred))

#3.using KNeighborsClassifier
knn_clf=KNeighborsClassifier()
model = knn_clf.fit(X_train,y_train)
knn_pred = model.predict(X_test)
cm=confusion_matrix(y_test,knn_pred)
#specify size of heatmap
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
print(classification_report(y_test,knn_pred))

#4.using MultinomialNB Naive Bayes
nb= MultinomialNB()
model = nb.fit(X_train,y_train)
nb_pred = model.predict(X_test)
cm=confusion_matrix(y_test,nb_pred)
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
print(classification_report(y_test,nb_pred))

#5.using Support Vector Machines
svm = SVC()
model = svm.fit(X_train,y_train)
svm_pred = model.predict(X_test)
cm=confusion_matrix(y_test,svm_pred)
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
print(classification_report(y_test,svm_pred))

#6.using XGBClassifier
xg_clf = XGBClassifier()
model = xg_clf.fit(X_train,y_train)
xg_pred = model.predict(X_test)
cm=confusion_matrix(y_test,xg_pred)
fig, ax = plt.subplots(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
print(classification_report(y_test,xg_pred))

"""By looking at the report logistic regression is the best performing model"""

#Example of prediction
log_pred = model.predict([[1,1,72,72,74,0.699634]])
log_pred

"""Using same dataset for Regression model to predict the performance score"""

#Splitting the data into independent and dependent variables
x=df1.drop(['lunch','gender','Performance_Level','Total_Performance_Score'],axis=1)
y=df1['Total_Performance_Score']
x

#splitting the data into train ,test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42, test_size = 0.2 )

from sklearn.linear_model import Ridge,Lasso,LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor,XGBRFRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVC, LinearSVC, SVR
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor

modelsr = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(random_state=42),
    'Lasso Regression ': Lasso(random_state=42),
    'Decision Tree Regression ': DecisionTreeRegressor(random_state=42, max_depth=5),
    'Random Forest': RandomForestRegressor(random_state=42, max_depth=5, n_estimators=10, max_features=1),
    'KNN Model ': KNeighborsRegressor(3),
    'Support Vector Machines (SVM)': SVR(gamma=2, C=1),
    'XGBRegressor': XGBRegressor(random_state=42)
}

for name,model in modelsr.items():
    model.fit(x_train,y_train)
    print(name + ' trained')

def get_rmse(y_true,y_pred):
    rmser = np.sqrt(np.mean((y_true-y_pred)**2))
    return rmser

for name,model in modelsr.items():
    y_predr = model.predict(x_train)
    rmser = get_rmse(y_train,y_predr)
    print(name + ' RMSE: {:.2f}'.format(rmser))

for name, model in modelsr.items():
    model.fit(x_train, y_train)
    y_predr = model.predict(x_train)
    MAEr = mae(y_train, y_predr)
    print(name + ' MAE: {:.2f}'.format(MAEr))

modelr = XGBRegressor()
modelr.fit(x_train, y_train)
y_test_predr = modelr.predict(x_test)
MAEr = mae(y_test,y_test_predr)
print('MAE :',MAEr)

#Example prediction
y_test_predr = modelr.predict([[1,1,1,72,72,74]])
y_test_predr

"""Dataset - teacher_performance_evaluation"""

df2.head()

df2['Attendance'] = df2.apply(lambda row: 'Present' if pd.notna(row['LoginTime']) and pd.notna(row['LogoutTime']) else 'Absent', axis=1)
df2.head()

df2.columns

df2.info()

"""EDA and Preprocessing for teacher_performance_evaluation

"""

df2.Qualification.value_counts()

df2.PunctualityScore.value_counts()

df2.StudentFeedbackScore.value_counts()

df2.ClassEngagementScore.value_counts()

df2.YearsOfExperience.value_counts()

#  data visualization from dataset 2
plt.figure(figsize=(6, 6))
sns.barplot(data=df2, y='OverallPerformanceScore', x='Qualification', palette='viridis')
plt.ylabel('OverallPerformanceScore', fontsize=14, family='serif')
plt.xlabel('Qualification', family='serif', fontsize=14, labelpad=10)
plt.xticks(family='serif')
plt.yticks(family='serif')
plt.title(label='Qualification vs OverallPerformanceScore', weight=200, family='serif', size=15, pad=12)
plt.show()

plt.figure(figsize=(15, 6))
sns.barplot(data=df2, y='PunctualityScore', x='OverallPerformanceScore', palette='viridis')
plt.ylabel('PunctualityScore', fontsize=14, family='serif')
plt.xlabel('OverallPerformanceScore', family='serif', fontsize=14, labelpad=10)
plt.xticks(family='serif')
plt.yticks(family='serif')
plt.title(label='PunctualityScore vs OverallPerformanceScore', weight=200, family='serif', size=15, pad=12)
plt.show()

plt.figure(figsize=(15, 6))
sns.barplot(data=df2, y='YearsOfExperience', x='OverallPerformanceScore', palette='viridis')
plt.ylabel('YearsOfExperience', fontsize=14, family='serif')
plt.xlabel('OverallPerformanceScore', family='serif', fontsize=14, labelpad=10)
plt.xticks(family='serif')
plt.yticks(family='serif')
plt.title(label='YearsOfExperience vs OverallPerformanceScore', weight=200, family='serif', size=15, pad=12)
plt.show()

plt.figure(figsize=(6, 6))
sns.barplot(data=df2, y='StudentFeedbackScore', x='ClassEngagementScore', palette='viridis')
plt.ylabel('StudentFeedbackScore', fontsize=14, family='serif')
plt.xlabel('ClassEngagementScore', family='serif', fontsize=14, labelpad=10)
plt.xticks(family='serif')
plt.yticks(family='serif')
plt.title(label='StudentFeedbackScore vs ClassEngagementScore', weight=200, family='serif', size=15, pad=12)
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(x='Qualification', palette="viridis", hue='StudentFeedbackScore',data=df2)
plt.title("Qualification Versus StudentFeedbackScore", fontsize = 20)

plt.figure(figsize=(10, 6))
sns.countplot(x='PunctualityScore', palette="viridis", hue='StudentFeedbackScore',data=df2)
plt.title("PunctualityScore Versus StudentFeedbackScore", fontsize = 20)

plt.figure(figsize=(10, 6))
sns.countplot(x='ClassEngagementScore', palette="viridis", hue='StudentFeedbackScore',data=df2)
plt.title("ClassEngagementScore Versus StudentFeedbackScore", fontsize = 20)

plt.figure(figsize=(6, 6))
sns.countplot(x='Attendance', palette="viridis", hue='StudentFeedbackScore',data=df2)
plt.title("Attendance Versus StudentFeedbackScore", fontsize = 20)

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df2, x='ClassEngagementScore', y='PunctualityScore', hue='StudentFeedbackScore', palette='viridis', s=100)
plt.title('ClassEngagementScore vs. PunctualityScore')
plt.xlabel('ClassEngagementScore')
plt.ylabel('PunctualityScore')
plt.legend(title='StudentFeedbackScore')

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df2, x='OverallPerformanceScore', y='YearsOfExperience', hue='StudentFeedbackScore', palette='viridis', s=100)
plt.title('OverallPerformanceScore vs. YearsOfExperience')
plt.xlabel('OverallPerformanceScore')
plt.ylabel('YearsOfExperience')
plt.legend(title='StudentFeedbackScore')

df2.describe()

"""Drop unwanted columns"""

df2.drop(['TeacherID','Date','LoginTime','LogoutTime'], axis=1, inplace=True)
df2

le1=LabelEncoder()
df2['Qualification']=le1.fit_transform(df2['Qualification'])
df2['Attendance']=le1.fit_transform(df2['Attendance'])
df2

"""To predict the Overall performance of Teachers"""

X1=df2.drop(['OverallPerformanceScore'], axis=1)
y1=df2['OverallPerformanceScore']

X1

#splitting the data into train ,test
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,random_state = 42, test_size = 0.2 )

print(X1_train.shape),print(y1_train.shape)
print(X1_test.shape),print(y1_test.shape)

"""Modeling and Evaluation"""

models1 = {
    'Linear Regression': LinearRegression(),
    'Ridge Regression': Ridge(random_state=42),
    'Lasso Regression ': Lasso(random_state=42),
    'Decision Tree Regression ': DecisionTreeRegressor(random_state=42, max_depth=5),
    'Random Forest': RandomForestRegressor(random_state=42, max_depth=5, n_estimators=10, max_features=1),
    'KNN Model ': KNeighborsRegressor(3),
    'Support Vector Machines (SVM)': SVR(gamma=2, C=1),
    'XGBRegressor': XGBRegressor(random_state=42)
}

for name,model in models1.items():
    model.fit(X1_train,y1_train)
    print(name + ' trained')

def get_rmse(y1_true,y1_pred):
    rmse1 = np.sqrt(np.mean((y1_true-y1_pred)**2))
    return rmse1

for name,model in models1.items():
    y1_pred = model.predict(X1_train)
    rmse1 = get_rmse(y1_train,y1_pred)
    print(name + ' RMSE: {:.2f}'.format(rmse1))

for name, model in models1.items():
    model.fit(X1_train, y1_train)
    y1_pred = model.predict(X1_train)
    MAE1 = mae(y1_train, y1_pred)
    print(name + ' MAE: {:.2f}'.format(MAE1))

"""By looking at the RMSE,MAE: XGBRegressor is the best performing model"""

model1 = XGBRegressor()
model1.fit(X1_train, y1_train)
y_test_pred1 = model1.predict(X1_test)
MAE1 = mae(y1_test,y_test_pred1)
print('MAE :',MAE1)

#Example prediction
y_test_pred1 = model1.predict([[9,9,7,4,8,0]])
y_test_pred1

"""dataset3 - smart_school_app_competitors"""

df3.head()

df3.columns

df3.info()

"""EDA and preprocessing"""

df3.UserRating.value_counts()

df3.PricingModel.value_counts()

df3.MarketShare.value_counts()

df3.OverallScore.value_counts()

plt.figure(figsize=(8,8))
df3['OverallScore'].value_counts().plot.pie(autopct='%1.1f%%')
plt.show()

df3['FeatureSet'].unique()

#univariate analysis of numerical columns - continuous variables -
df3[['UserRating','OverallScore']].hist(figsize=(10,6))
plt.show()

df3.describe()

# This barplot show the top 10 CompetitorName
sorted_df = df3.sort_values(by='UserRating', ascending=False)
# Select the top 10 competitors
top_10_competitors = sorted_df.head(10)
# Create a bar chart to visualize their ratings
plt.figure(figsize=(10, 6))
plt.bar(top_10_competitors['CompetitorName'], top_10_competitors['UserRating'])
plt.xlabel('Competitors')
plt.ylabel('User Rating')
plt.title('Top 10 Competitors by User Rating')
plt.xticks(rotation=45)  # Rotate x-axis labels for readability

# Show the plot
plt.tight_layout()
plt.show()

# This barplot show the top 10 CompetitorName
sorted_df = df3.sort_values(by='OverallScore', ascending=False)
# Select the top 10 competitors
top_10_competitors = sorted_df.head(10)
# Create a bar chart to visualize their ratings
plt.figure(figsize=(10, 6))
plt.bar(top_10_competitors['CompetitorName'], top_10_competitors['OverallScore'])
plt.xlabel('Competitors')
plt.ylabel('OverallScore')
plt.title('Top 10 Competitors by OverallScore')
plt.xticks(rotation=45)  # Rotate x-axis labels for readability
# Show the plot
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 6))
sns.scatterplot(x='CompetitorName',y='OverallScore',hue='PricingModel',data=df3)
plt.title("CompetitorName,Overallscore and PricingModel", fontsize = 10)
plt.xticks(rotation=90);

#Boxplot for numerical column
for i in ['UserRating','OverallScore']:
    plt.figure()
    plt.boxplot(df3[i])
    plt.title(i)

#Drop unwanted columns
df3.drop(['CompetitorID'],axis=1,inplace=True)

#use LabelEncoder to categorical columns
le3=LabelEncoder()
df3['CompetitorName']=le3.fit_transform(df3['CompetitorName'])
df3['FeatureSet']=le3.fit_transform(df3['FeatureSet'])
df3['PricingModel']=le3.fit_transform(df3['PricingModel'])
df3['MarketShare']=le3.fit_transform(df3['MarketShare'])
df3['KeyStrengths']=le3.fit_transform(df3['KeyStrengths'])
df3['KeyWeaknesses']=le3.fit_transform(df3['KeyWeaknesses'])
df3

"""To do market segmentation Analysis for the Competitors"""

# selecting features for building a model
X2=df3[['CompetitorName','FeatureSet','PricingModel','UserRating','MarketShare','KeyStrengths','KeyWeaknesses']]
X2.head()

# feature scaling
scaler = StandardScaler()
X2_scaled = scaler.fit_transform(X2)

# applying Principle Component Analysis (PCA)
pca = PCA(n_components=7)
X2_pca = pca.fit_transform(X2_scaled)
df3_pca = pd.DataFrame(X2_pca, columns=['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6','PC7'])
df3_pca.head()

PCAsummary = pd.DataFrame({'Standard Deviation':df3_pca.std(),
                           'Proportion of Variance': pca.explained_variance_ratio_,
                           'Cumultive Proportion': pca.explained_variance_ratio_.cumsum()})
PCAsummary

df3_p=pca.fit(X2_scaled)
# correlation coefficient between original variables and the component
index=['PC1','PC2','PC3','PC4','PC5','PC6','PC7']
rot_matrix = df3_p.components_.T
rot_df = pd.DataFrame(rot_matrix, index=X2.columns.values, columns=index)
rot_df=round(-rot_df,3)
rot_df

# correlation matrix plot for loadings
plt.rcParams['figure.figsize'] = (20,15)
ax = sns.heatmap(rot_df, annot=True, cmap='Greens')
plt.show()

# get PC scores
pca_scores = X2_pca
loadings = pca.components_
# get 2D biplot
cluster.biplot(cscore=pca_scores, loadings=loadings, labels=X2.columns.values, var1=0,var2=0, show=True,dim=(10,5))

"""Extracting Segments

K-Means clustering analysis K-Means clustering is an unsupervised machine learning algorithm that groups data points into k distinct clusters based on their similarity. It's an iterative process that aims to minimize the within-cluster sum of squares, meaning it tries to create clusters where data points within each group are as close as possible to each other and far from points in other groups.This algorithm helps us identify the optimal number of clusters by generating an "elbow curve."
"""

np.random.seed(90)
nrep = 10
num_segments = range(1, 8)
wcss = []
X2_k = {}
for k in num_segments:
  # Create a KMeans object with 'k' clusters, 'n_init' repetitions, and a fixed random seed for reproducibility.
    kmeans = KMeans(n_clusters=k, n_init=nrep, random_state=90)
    # Fit the KMeans model on the original DataFrame 'X2'.
    kmeans.fit(X2)
    # Calculate and store the sum of within-cluster distances (inertia) for the current number of clusters.
    wcss.append((kmeans.inertia_))
    # Store the KMeans model in the 'X2_k' dictionary, indexed by the number of clusters.
    X2_k[str(k)] = kmeans
    # Create a bar plot to visualize the sum of within-cluster distances for different numbers of clusters.
plt.bar(num_segments, wcss)
# Add labels and a title to the plot for better interpretation.
plt.xlabel("Number of segments")
plt.ylabel("Sum of within-cluster distances")
plt.title("Segmentation Results")
# Display the plot showing the relationship between the number of clusters and within-cluster distances.
plt.show()

# plotting the results of Elbow

wcss = []

for i in range(1, 12):
  kmean = KMeans(n_clusters=i, init='k-means++', random_state=90)
  kmean.fit(X2_pca)
  wcss.append(kmean.inertia_)

plt.figure(figsize=(8,6))
plt.title('Plot of the Elbow Method', size=15, family='serif')
plt.plot(range(1, 12), wcss)
plt.xticks(range(1, 12), family='serif')
plt.yticks(family='serif')
plt.xlabel('Number of Custers (K)', family='serif')
plt.ylabel('WCSS', family='serif')
plt.grid()
plt.tick_params(axis='both', direction='inout', length=6, color='purple', grid_color='lightgray', grid_linestyle='--')
plt.show()

model = KMeans(n_clusters=i, init='k-means++', random_state=90)
visualizer = KElbowVisualizer(model, k=(1, 12))
visualizer.fit(X2_scaled)

# Display the elbow p
visualizer.show()

"""Based on the elbow method, the optimal number of clusters for the given data is likely k=3. This means that the KMeans algorithm can effectively group the data points into three distinct clusters with minimal distortion."""

# Applying K-means clustering
kmeans = KMeans(n_clusters=3,random_state=90)
df3['Cluster'] = kmeans.fit_predict(X2_scaled)

# analyze the clusters
print(df3['Cluster'].value_counts())

#Model Evaluation
kmeans = KMeans(n_clusters=3, init='k-means++', random_state=90).fit(X2_scaled)
df3['Cluster Number'] = kmeans.labels_
# Label assigned for each data point
print (kmeans.labels_)

# Gives within-cluster sum of squares.
print (kmeans.inertia_)

# Number of iterations that k-means algorithm runs to get a minimum within-cluster sum of squares
print(kmeans.n_iter_)

# Location of the centroids on each cluster.
print(kmeans.cluster_centers_)

"""Profiling Segments"""

kmeans = KMeans(n_clusters=3,random_state=90)

# Fit the KMeans model on the data 'df3'.
# The 'fit' function identifies the cluster centers and assigns data points to their respective clusters.
kmeans.fit(df3)

# Create a PCA model with 2 principal components.
# 'n_components=2' specifies that the data should be transformed into a 2-dimensional space.
pca = PCA(n_components=2)
df3_pca = pca.fit_transform(df3)
# Create a new figure and axis for the scatter plot.
fig, ax = plt.subplots(figsize=(10, 6))
ax.scatter(df3_pca[:, 0], df3_pca[:, 1])

# Set the labels for the x-axis and y-axis.
ax.set_xlabel('Principal Component 1')
ax.set_ylabel('Principal Component 2')

# Display the plot.
plt.show()

pca = PCA(n_components=2)
X2_pca = pca.fit_transform(X2_scaled)

# Convert PCA results to DataFrame
X2_pca_df = pd.DataFrame(data=X2_pca, columns=['PC1', 'PC2'])
kmeans = KMeans(n_clusters=3, random_state=90)
kmeans.fit(X2_pca_df)
plt.figure(figsize=(10,8))
sns.scatterplot(data=X2_pca_df, x="PC1", y="PC2", hue=kmeans.labels_)
plt.scatter(kmeans.cluster_centers_[:,1], kmeans.cluster_centers_[:,0],
            marker="X", c="r", s=80, label="centroids")
plt.legend()

features = X2[['CompetitorName','FeatureSet','PricingModel','UserRating','MarketShare','KeyStrengths','KeyWeaknesses']]
kmeans = KMeans(n_clusters=3, random_state=90)
X2['Segment'] = kmeans.fit_predict(features)
# Analyze the segments
print(X2.groupby('Segment').mean())

# Plot the segments
plt.figure(figsize = (12,4))
sns.scatterplot(x='CompetitorName', y='UserRating', hue='Segment', palette='viridis',data=X2)
plt.title('Segmentation of Competitors in the Market')
plt.show()

"""Target Segment"""

overallscore = df3.groupby('Cluster Number')['OverallScore'].mean()
overallscore = overallscore.to_frame().reset_index()
overallscore

marketshare = df3.groupby('Cluster Number')['MarketShare'].mean()
marketshare = marketshare.to_frame().reset_index()
marketshare

user_rating = df3.groupby('Cluster Number')['UserRating'].mean()
user_rating = user_rating.to_frame().reset_index()
user_rating

pricing_model = df3.groupby('Cluster Number')['PricingModel'].mean()
pricing_model = pricing_model.to_frame().reset_index()
pricing_model

feature = df3.groupby('Cluster Number')['FeatureSet'].mean()
feature = feature.to_frame().reset_index()
feature

competitor_name = df3.groupby('Cluster Number')['CompetitorName'].mean()
competitor_name = competitor_name.to_frame().reset_index()
competitor_name

key_strengths = df3.groupby('Cluster Number')['KeyStrengths'].mean()
key_strengths = key_strengths.to_frame().reset_index()
key_strengths

segment = marketshare.merge(user_rating, on='Cluster Number', how='left').merge(overallscore, on='Cluster Number', how='left')
print(segment)
plt.figure(figsize = (12,4))
sns.scatterplot(x="OverallScore", y="UserRating", data=segment, hue='Cluster Number',s=400, palette='coolwarm')
plt.title("Simple segment evaluation plot", fontsize=15)
plt.xlabel("Overallscore", fontsize=10)
plt.ylabel("UserRating", fontsize=10)
plt.legend(title='segment')
plt.show()

segment = pricing_model.merge(competitor_name, on='Cluster Number', how='left').merge(overallscore, on='Cluster Number', how='left')
print(segment)
plt.figure(figsize = (12,4))
sns.scatterplot(x="CompetitorName", y="OverallScore", data=segment, hue='Cluster Number',s=400, palette='coolwarm')
plt.title("Simple segment evaluation plot", fontsize=15)
plt.xlabel("CompetitorName", fontsize=10)
plt.ylabel("Overallscore", fontsize=10)
plt.legend(title='segment')
plt.show()

segment = feature.merge(competitor_name, on='Cluster Number', how='left').merge(key_strengths, on='Cluster Number', how='left')
print(segment)
plt.figure(figsize = (12,4))
sns.scatterplot(x="CompetitorName", y="KeyStrengths", data=segment, hue='Cluster Number',s=400, palette='coolwarm')
plt.title("Simple segment evaluation plot", fontsize=15)
plt.xlabel("CompetitorName", fontsize=10)
plt.ylabel("KeyStrengths", fontsize=10)
plt.legend(title='segment')
plt.show()

